POST http://localhost:8080/auth/register
Accept: application/json
Content-Type: application/json

{
    "email": "admin1@example.com",
    "password": "admin",
    "nombre": "admin",
    "apellido": "admin",
    "idPuesto": 1
}